### PR TITLE
[WIP] Fix TravisCI builds.

### PR DESCRIPTION
**Pull request by lucasmichot**
Fix TravisCI builds.

### CODE REVIEW

**Comment by lucasmichot** [comment]
?????? @gizburdt the build is not even over !!

**Comment by gizburdt** [comment]
Whoops, sorry!

**Comment by lucasmichot** [comment]
And it's not even fixed and this PR was set as Work In Progress

**Comment by gizburdt** [comment]
No version tagged yet, so no worries

**Comment by gizburdt** [comment]
Please proceed, I will wait till the build is done

**Comment by gizburdt** [comment]
I thought this was needed to test the other PR. Missed the [WIP] in the title, sorry. Thanks for the help! :)

**Pull request merged**
